## Loading the standard libraries

In [1]:
import pandas as pd
import numpy as np

## Loading the data

In [2]:
data = pd.read_csv('Sachin_ODI.csv')
data.head()

runs  NotOut mins  bf  fours  sixes      sr  Inns           Opp    Ground  \
0    13       0   30  15      3      0   86.66     1   New Zealand    Napier   
1    37       0   75  51      3      1   72.54     2  South Africa  Hamilton   
2    47       0   65  40      7      0  117.50     2     Australia   Dunedin   
3    48       0   37  30      9      1  160.00     2    Bangladesh   Sharjah   
4     4       0   13   9      1      0   44.44     2      Pakistan   Sharjah   

         Date        Winner    Won  century  
0  1995-02-16   New Zealand  False    False  
1  1995-02-18  South Africa  False    False  
2  1995-02-22         India   True    False  
3  1995-04-05         India   True    False  
4  1995-04-07      Pakistan  False    False

In [3]:
data.shape

(360, 14)

## Observations:

- We are looking at 360 ODI matches played by Sachin
- sr means strike rate
- bf means balls faced

In [4]:
data = data.drop(['Ground', 'Date'], axis = 1)
data.head()

runs  NotOut mins  bf  fours  sixes      sr  Inns           Opp  \
0    13       0   30  15      3      0   86.66     1   New Zealand   
1    37       0   75  51      3      1   72.54     2  South Africa   
2    47       0   65  40      7      0  117.50     2     Australia   
3    48       0   37  30      9      1  160.00     2    Bangladesh   
4     4       0   13   9      1      0   44.44     2      Pakistan   

         Winner    Won  century  
0   New Zealand  False    False  
1  South Africa  False    False  
2         India   True    False  
3         India   True    False  
4      Pakistan  False    False

1. If total matches played in the dataset is 360, it means that the total Sample Space = 360

## How to get the Sample Space of the data:

In [5]:
data.shape[0]

360

In [6]:
len(data)

360

## Event A : India winning the match

In [7]:
## Getting the sample space for event A

data['Won'].value_counts()

True     184
False    176
Name: Won, dtype: int64

1. The Sample Space for India winning the match is 184

## Probability of Event A :

In [9]:
## Basic Approach or manual approach

184 / 360

0.5111111111111111

In [10]:
## Pandas Approach

df_won = data[data['Won'] == True]
df_won.head()

runs  NotOut mins   bf  fours  sixes      sr  Inns          Opp Winner  \
2    47       0   65   40      7      0  117.50     2    Australia  India   
3    48       0   37   30      9      1  160.00     2   Bangladesh  India   
5   112       1  137  107     15      1  104.67     2    Sri Lanka  India   
6    41       0   51   41      5      0  100.00     2    Sri Lanka  India   
8    39       0   79   51      4      0   76.47     2  New Zealand  India   

    Won  century  
2  True    False  
3  True    False  
5  True     True  
6  True    False  
8  True    False

In [11]:
df_won.shape

(184, 12)

In [14]:
p_a = len(df_won) / len(data)
p_a

0.5111111111111111

## Observation:

- 0.51 (probability) represents that 50% is the winning rate for India

## Probability of losing

In [15]:
1 - p_a

0.48888888888888893

## Observation:

- Probability of losing is negative of Probability of winning
- P(A') = 1 - P(A)                [A' means A complement]